import { DomainConfig } from "@/lib/domains";

export const welfareDomain: DomainConfig = {
    value: "welfare",
    label: "Govt. Welfare",
    description: "Government scheme eligibility and benefit disbursement simulation",
    defaultThreshold: 0.48,
    fields: [
        { key: "name", label: "Applicant Name", type: "text", placeholder: "Lakshmi Devi" },
        {
            key: "category",
            label: "Social Category",
            type: "select",
            options: ["General", "OBC", "SC", "ST", "EWS"],
        },
        {
            key: "gender",
            label: "Gender",
            type: "select",
            options: ["Female", "Male", "Other"],
        },
        {
            key: "state_tier",
            label: "State / Region",
            type: "select",
            options: ["Metro State", "Developed State", "Developing State", "Remote Region"],
        },
        { key: "annual_income", label: "Annual Income (₹L)", type: "number", min: 0, max: 15 },
        { key: "family_size", label: "Family Size", type: "number", min: 1, max: 20 },
        { key: "land_holding", label: "Land Holding (acres)", type: "number", min: 0, max: 20 },
        {
            key: "employment_status",
            label: "Employment Status",
            type: "select",
            options: ["Employed", "Self-employed", "Daily Wage", "Unemployed"],
        },
        {
            key: "housing_status",
            label: "Housing Status",
            type: "select",
            options: ["Owns Home", "Renting", "Homeless"],
        },
        {
            key: "aadhaar_linked",
            label: "Aadhaar Linked",
            type: "select",
            options: ["Yes", "No"],
        },
    ],
    defaultProfile: {
        name: "Lakshmi Devi",
        category: "OBC",
        gender: "Female",
        state_tier: "Developing State",
        annual_income: 1.2,
        family_size: 4,
        land_holding: 2,
        employment_status: "Daily Wage",
        housing_status: "Renting",
        aadhaar_linked: "Yes",
    },
    variationLabels: {
        baseline: "Original Applicant",
        gender_swap: "Gender Changed",
        location_change: "Region Changed",
        category_change: "Category Changed",
    },
    presets: [
        {
            id: "rural-farmer-borderline",
            title: "Rural Farmer Borderline",
            description: "A small farmer in a remote region sitting right at the eligibility cutoff. Tests whether region and category affect the final decision.",
            threshold: 0.48,
            profile: {
                name: "Mohan Patel",
                category: "OBC",
                gender: "Male",
                state_tier: "Remote Region",
                annual_income: 1.8,
                family_size: 5,
                land_holding: 3,
                employment_status: "Self-employed",
                housing_status: "Owns Home",
                aadhaar_linked: "Yes",
            },
        },
        {
            id: "ews-urban-applicant",
            title: "EWS Urban Applicant",
            description: "Urban EWS applicant with no land. Tests whether the system treats city-based poor applicants the same as rural ones.",
            threshold: 0.48,
            profile: {
                name: "Fatima Khan",
                category: "EWS",
                gender: "Female",
                state_tier: "Metro State",
                annual_income: 2.1,
                family_size: 3,
                land_holding: 0,
                employment_status: "Unemployed",
                housing_status: "Renting",
                aadhaar_linked: "Yes",
            },
        },
    ],
};
